version: '2'
services:
  dev:
    build: ./
    volumes:
      - '.:/docs'
      - npm-app:/docs/node_modules
    ports:
      - '8080:8080'
    command: 'npm run start'

volumes:
  npm-app:
    driver: local
